export const CIE10: Record<string, string> = {
  "F00": "Demencia en la enfermedad de Alzheimer",
  "F01": "Demencia vascular",
  "F02": "Demencia en otras enfermedades",
  "F03": "Demencia sin especificación",
  "F04": "Síndrome amnésico orgánico",
  "F05": "Delirium no inducido por alcohol",
  "F06": "Otros trastornos mentales orgánicos",
  "F07": "Trastornos de personalidad orgánicos",
  "F09": "Trastorno mental orgánico sin especificación",
  "F10": "Trastornos por uso de alcohol",
  "F11": "Trastornos por uso de opioides",
  "F12": "Trastornos por uso de cannabinoides",
  "F13": "Trastornos por uso de sedantes e hipnóticos",
  "F14": "Trastornos por uso de cocaína",
  "F15": "Trastornos por uso de estimulantes",
  "F16": "Trastornos por uso de alucinógenos",
  "F17": "Trastornos por uso de tabaco",
  "F18": "Trastornos por uso de disolventes volátiles",
  "F19": "Trastornos por uso de múltiples sustancias",
  "F20": "Esquizofrenia",
  "F21": "Trastorno esquizotípico",
  "F22": "Trastornos delirantes persistentes",
  "F23": "Trastornos psicóticos agudos y transitorios",
  "F24": "Trastorno delirante inducido",
  "F25": "Trastornos esquizoafectivos",
  "F28": "Otros trastornos psicóticos no orgánicos",
  "F29": "Psicosis no orgánica sin especificación",
  "F30": "Episodio maníaco",
  "F31": "Trastorno afectivo bipolar",
  "F32": "Episodio depresivo",
  "F33": "Trastorno depresivo recurrente",
  "F34": "Trastornos del humor persistentes",
  "F38": "Otros trastornos del humor",
  "F39": "Trastorno del humor sin especificación",
  "F40": "Trastornos de ansiedad fóbica",
  "F40.0": "Agorafobia",
  "F40.1": "Fobias sociales",
  "F40.2": "Fobias específicas",
  "F41": "Otros trastornos de ansiedad",
  "F41.0": "Trastorno de pánico",
  "F41.1": "Trastorno de ansiedad generalizada",
  "F41.2": "Trastorno mixto ansioso-depresivo",
  "F42": "Trastorno obsesivo-compulsivo",
  "F43": "Reacciones al estrés grave y trastornos de adaptación",
  "F43.0": "Reacción aguda al estrés",
  "F43.1": "Trastorno de estrés postraumático",
  "F43.2": "Trastorno de adaptación",
  "F44": "Trastornos disociativos",
  "F45": "Trastornos somatomorfos",
  "F48": "Otros trastornos neuróticos",
  "F50": "Trastornos de la conducta alimentaria",
  "F50.0": "Anorexia nerviosa",
  "F50.2": "Bulimia nerviosa",
  "F51": "Trastornos del sueño no orgánicos",
  "F52": "Disfunciones sexuales",
  "F54": "Factores psicológicos en enfermedades físicas",
  "F55": "Abuso de sustancias no dependientes",
  "F59": "Trastornos del comportamiento asociados a disfunciones",
  "F60": "Trastornos específicos de la personalidad",
  "F60.0": "Trastorno paranoide de la personalidad",
  "F60.1": "Trastorno esquizoide de la personalidad",
  "F60.2": "Trastorno disocial de la personalidad",
  "F60.3": "Trastorno de inestabilidad emocional",
  "F60.4": "Trastorno histriónico de la personalidad",
  "F60.5": "Trastorno anancástico de la personalidad",
  "F60.6": "Trastorno ansioso de la personalidad",
  "F60.7": "Trastorno dependiente de la personalidad",
  "F61": "Trastornos mixtos de la personalidad",
  "F62": "Cambios de personalidad no debidos a lesión cerebral",
  "F63": "Trastornos de los hábitos y del control de impulsos",
  "F64": "Trastornos de la identidad sexual",
  "F65": "Trastornos de la inclinación sexual",
  "F66": "Trastornos del desarrollo psicológico sexual",
  "F68": "Otros trastornos de la personalidad",
  "F70": "Retraso mental leve",
  "F71": "Retraso mental moderado",
  "F72": "Retraso mental grave",
  "F73": "Retraso mental profundo",
  "F78": "Otros tipos de retraso mental",
  "F79": "Retraso mental sin especificación",
  "F80": "Trastornos del desarrollo del habla y del lenguaje",
  "F81": "Trastornos del desarrollo del aprendizaje escolar",
  "F82": "Trastorno del desarrollo de la función motriz",
  "F83": "Trastornos del desarrollo mixtos",
  "F84": "Trastornos del desarrollo psicológico generalizados",
  "F84.0": "Autismo infantil",
  "F84.5": "Síndrome de Asperger",
  "F90": "Trastornos hipercinéticos",
  "F90.0": "Trastorno de actividad y atención (TDAH)",
  "F91": "Trastornos disociales",
  "F92": "Trastornos disociales y de las emociones mixtos",
  "F93": "Trastornos de las emociones en la infancia",
  "F94": "Trastornos del comportamiento social en la infancia",
  "F95": "Trastornos por tics",
  "F98": "Otros trastornos conductuales en la infancia",
  "F99": "Trastorno mental sin especificación",
  "Z00": "Examen médico general",
  "Z03": "Observación y evaluación médica",
  "Z04": "Examen por otras razones",
  "Z09": "Examen de seguimiento",
  "Z13": "Examen de detección de otras enfermedades",
  "Z50": "Atención en procedimientos de rehabilitación",
  "Z60": "Problemas relacionados con el ambiente social",
  "Z61": "Problemas relacionados con eventos negativos en la infancia",
  "Z62": "Otros problemas relacionados con la crianza",
  "Z63": "Problemas relacionados con el grupo de apoyo",
  "Z65": "Problemas relacionados con circunstancias psicosociales",
  "Z71": "Personas en contacto con servicios de salud para consejería",
  "Z73": "Problemas relacionados con dificultades de organización de vida",
  "Z81": "Historia familiar de trastornos mentales"
}

export function buscarCIE10(query: string): { codigo: string; nombre: string }[] {
  if (!query || query.length < 2) return []
  const q = query.toUpperCase()
  return Object.entries(CIE10)
    .filter(([codigo, nombre]) => 
      codigo.startsWith(q) || nombre.toLowerCase().includes(query.toLowerCase())
    )
    .slice(0, 8)
    .map(([codigo, nombre]) => ({ codigo, nombre }))
}

export function getNombreCIE10(codigo: string): string {
  return CIE10[codigo.toUpperCase()] || ''
}
